name: MATV Bangla News Bot Engine

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  run-matv-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bangla Fonts & Graphic Canvas Engine
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev pango1.0-dev libjpeg-dev libgif-dev librsvg2-dev fonts-noto-core

      - name: Install NPM Modules
        run: npm install

      - name: Execute M,A TV Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node bot.js

      - name: Clean Old Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0 # শেষ বা বন্ধ হয়ে যাওয়া আগের সব Run সাথে সাথে মুছে দেবে
          keep_minimum_runs: 1 # শুধু সবচেয়ে শেষ রানটি ধরে রাখবে
