name: MATV News Bot Service

on:
  schedule:
    # প্রতি ১ ঘণ্টা পর পর নতুন ওয়ার্কফ্লো সেশন রিফ্রেশ করবে
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  run-matv-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Graphic Engine
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev pango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install Dependencies
        run: npm install

      - name: Execute M,A TV Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node bot.js
